using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace UnityEngine {
public class AssetUtility {
	// Mock data:
	private Dictionary<string, int> m_functionCallCounts;
	public Dictionary<string, int> FunctionCallCounts {
		get { 
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			return m_functionCallCounts;
		}
	}

	public static UnityEngine.Object CreateEngineObject( System.String className ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static void CreateAsset( UnityEngine.Object theAsset, System.String assetName, System.String extension ){
	}

	public static void CreateAsset( UnityEngine.Object theAsset, System.String assetName ){
	}

	public static void AddAssetToSameFile( UnityEngine.Object newAsset, UnityEngine.Object sameAssetFile ){
	}

	public static void SaveAsset( UnityEngine.Object newAsset ){
	}

	public static UnityEngine.Object LoadWithPathAndFileID( System.String path, System.Int32 i ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 GetObjectCountAtPath( System.String path ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public AssetUtility( ){
		//Mock Data:
			m_functionCallCounts = new Dictionary<string, int>();
		if(!m_functionCallCounts.ContainsKey( "Void .ctor()" )){
			m_functionCallCounts.Add( "Void .ctor()", 0 );
		}
		m_functionCallCounts["Void .ctor()"]++;
			
	}
}
}
