using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace UnityEngine {
public class Debug {
	// Mock data:
	private Dictionary<string, int> m_functionCallCounts;
	public Dictionary<string, int> FunctionCallCounts {
		get { 
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			return m_functionCallCounts;
		}
	}

	public static void DrawLine(UnityEngine.Vector3 start, UnityEngine.Vector3 end, UnityEngine.Color color) {
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static void DrawLine(UnityEngine.Vector3 start, UnityEngine.Vector3 end) {
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static void DrawRay(UnityEngine.Vector3 start, UnityEngine.Vector3 dir) {
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static void DrawRay(UnityEngine.Vector3 start, UnityEngine.Vector3 dir, UnityEngine.Color color) {
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static void Break() {
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static void Log(System.Object message) {
		Console.WriteLine(message);
	}

	public static void Log(System.Object message, UnityEngine.Object context) {
		Console.WriteLine(message);
	}

	public static void LogError(System.Object message) {
		Console.Error.WriteLine(message);
	}

	public static void LogError(System.Object message, UnityEngine.Object context) {
		Console.Error.WriteLine(message);
	}

	public static void LogWarning(System.Object message) {
		Console.WriteLine(message);
	}

	public static void LogWarning(System.Object message, UnityEngine.Object context) {
		Console.WriteLine(message);
	}

	public Debug( ){
		//Mock Data:
			m_functionCallCounts = new Dictionary<string, int>();
		if(!m_functionCallCounts.ContainsKey( "Void .ctor()" )){
			m_functionCallCounts.Add( "Void .ctor()", 0 );
		}
		m_functionCallCounts["Void .ctor()"]++;
			
	}

	public static System.Boolean isDebugBuild {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}
}
}
