using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace UnityEngine {
public class GUILayout {
	// Mock data:
	private Dictionary<string, int> m_functionCallCounts;
	public Dictionary<string, int> FunctionCallCounts {
		get { 
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			return m_functionCallCounts;
		}
	}

	public static void Label( UnityEngine.Texture image, UnityEngine.GUILayoutOption[] options ){
	}

	public static void Label(System.String text) {
	}

	public static void Label(System.String text, UnityEngine.GUILayoutOption option) {
	}

	public static void Label( System.String text, UnityEngine.GUILayoutOption[] options ){
	}

	public static void Label( UnityEngine.GUIContent content, UnityEngine.GUILayoutOption[] options ){
	}

	public static void Label( UnityEngine.Texture image, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
	}

	public static void Label( System.String text, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
	}

	public static void Label( UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
	}

	public static void Box( UnityEngine.Texture image, UnityEngine.GUILayoutOption[] options ){
	}

	public static void Box( System.String text, UnityEngine.GUILayoutOption[] options ){
	}

	public static void Box( UnityEngine.GUIContent content, UnityEngine.GUILayoutOption[] options ){
	}

	public static void Box( UnityEngine.Texture image, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
	}

	public static void Box( System.String text, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
	}

	public static void Box( UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
	}

	public static System.Boolean Button( UnityEngine.Texture image, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean Button(System.String text) {
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean Button(System.String text, UnityEngine.GUILayoutOption option) {
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean Button( System.String text, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean Button( UnityEngine.GUIContent content, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean Button( UnityEngine.Texture image, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean Button( System.String text, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean Button( UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean RepeatButton( UnityEngine.Texture image, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean RepeatButton( System.String text, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean RepeatButton( UnityEngine.GUIContent content, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean RepeatButton( UnityEngine.Texture image, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean RepeatButton( System.String text, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean RepeatButton( UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.String TextField(System.String text) {
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.String TextField(System.String text, UnityEngine.GUILayoutOption option) {
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.String TextField( System.String text, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.String TextField( System.String text, System.Int32 maxLength, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.String TextField( System.String text, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.String TextField( System.String text, System.Int32 maxLength, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.String PasswordField( System.String password, System.Char maskChar, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.String PasswordField( System.String password, System.Char maskChar, System.Int32 maxLength, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.String PasswordField( System.String password, System.Char maskChar, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.String PasswordField( System.String password, System.Char maskChar, System.Int32 maxLength, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.String TextArea( System.String text, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.String TextArea( System.String text, System.Int32 maxLength, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.String TextArea( System.String text, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.String TextArea( System.String text, System.Int32 maxLength, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean Toggle( System.Boolean value, UnityEngine.Texture image, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean Toggle( System.Boolean value, System.String text, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean Toggle( System.Boolean value, UnityEngine.GUIContent content, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean Toggle( System.Boolean value, UnityEngine.Texture image, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean Toggle( System.Boolean value, System.String text, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean Toggle( System.Boolean value, UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 Toolbar( System.Int32 selected, System.String[] texts, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 Toolbar( System.Int32 selected, UnityEngine.Texture[] images, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 Toolbar( System.Int32 selected, UnityEngine.GUIContent[] content, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 Toolbar( System.Int32 selected, System.String[] texts, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 Toolbar( System.Int32 selected, UnityEngine.Texture[] images, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 Toolbar( System.Int32 selected, UnityEngine.GUIContent[] contents, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 SelectionGrid( System.Int32 selected, System.String[] texts, System.Int32 xCount, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 SelectionGrid( System.Int32 selected, UnityEngine.Texture[] images, System.Int32 xCount, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 SelectionGrid( System.Int32 selected, UnityEngine.GUIContent[] content, System.Int32 xCount, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 SelectionGrid( System.Int32 selected, System.String[] texts, System.Int32 xCount, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 SelectionGrid( System.Int32 selected, UnityEngine.Texture[] images, System.Int32 xCount, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 SelectionGrid( System.Int32 selected, UnityEngine.GUIContent[] contents, System.Int32 xCount, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Single HorizontalSlider( System.Single value, System.Single leftValue, System.Single rightValue, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Single HorizontalSlider( System.Single value, System.Single leftValue, System.Single rightValue, UnityEngine.GUIStyle slider, UnityEngine.GUIStyle thumb, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Single VerticalSlider( System.Single value, System.Single leftValue, System.Single rightValue, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Single VerticalSlider( System.Single value, System.Single leftValue, System.Single rightValue, UnityEngine.GUIStyle slider, UnityEngine.GUIStyle thumb, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Single HorizontalScrollbar( System.Single value, System.Single size, System.Single leftValue, System.Single rightValue, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Single HorizontalScrollbar( System.Single value, System.Single size, System.Single leftValue, System.Single rightValue, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Single VerticalScrollbar( System.Single value, System.Single size, System.Single topValue, System.Single bottomValue, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Single VerticalScrollbar( System.Single value, System.Single size, System.Single topValue, System.Single bottomValue, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static void Space( System.Single pixels ){
	}

	public static void FlexibleSpace( ){
	}
	
	public static void BeginHorizontal() {
	}

	public static void BeginHorizontal( UnityEngine.GUILayoutOption[] options ){
	}

	public static void BeginHorizontal( UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
	}

	public static void EndHorizontal( ){
	}

	public static void BeginVertical( UnityEngine.GUILayoutOption[] options ){
	}

	public static void BeginVertical( UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
	}

	public static void EndVertical( ){
	}

	public static void BeginArea( UnityEngine.Rect screenRect ){
	}

	public static void BeginArea( UnityEngine.Rect screenRect, System.String text ){
	}

	public static void BeginArea( UnityEngine.Rect screenRect, UnityEngine.Texture image ){
	}

	public static void BeginArea( UnityEngine.Rect screenRect, UnityEngine.GUIContent content ){
	}

	public static void BeginArea( UnityEngine.Rect screenRect, UnityEngine.GUIStyle style ){
	}

	public static void BeginArea( UnityEngine.Rect screenRect, System.String text, UnityEngine.GUIStyle style ){
	}

	public static void BeginArea( UnityEngine.Rect screenRect, UnityEngine.Texture image, UnityEngine.GUIStyle style ){
	}

	public static void BeginArea( UnityEngine.Rect screenRect, UnityEngine.GUIContent content, UnityEngine.GUIStyle style ){
	}

	public static void EndArea( ){
	}

	public static UnityEngine.Vector2 BeginScrollView( UnityEngine.Vector2 scrollPosition, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.Vector2 BeginScrollView( UnityEngine.Vector2 scrollPosition, System.Boolean alwaysShowHorizontal, System.Boolean alwaysShowVertical, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.Vector2 BeginScrollView( UnityEngine.Vector2 scrollPosition, UnityEngine.GUIStyle horizontalScrollbar, UnityEngine.GUIStyle verticalScrollbar, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.Vector2 BeginScrollView( UnityEngine.Vector2 scrollPosition, UnityEngine.GUIStyle style ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.Vector2 BeginScrollView( UnityEngine.Vector2 scrollPosition, System.Boolean alwaysShowHorizontal, System.Boolean alwaysShowVertical, UnityEngine.GUIStyle horizontalScrollbar, UnityEngine.GUIStyle verticalScrollbar, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.Vector2 BeginScrollView( UnityEngine.Vector2 scrollPosition, System.Boolean alwaysShowHorizontal, System.Boolean alwaysShowVertical, UnityEngine.GUIStyle horizontalScrollbar, UnityEngine.GUIStyle verticalScrollbar, UnityEngine.GUIStyle background, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static void EndScrollView( ){
	}

	public static UnityEngine.Rect Window( System.Int32 id, UnityEngine.Rect screenRect, UnityEngine.GUI.WindowFunction func, System.String text, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.Rect Window( System.Int32 id, UnityEngine.Rect screenRect, UnityEngine.GUI.WindowFunction func, UnityEngine.Texture image, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.Rect Window( System.Int32 id, UnityEngine.Rect screenRect, UnityEngine.GUI.WindowFunction func, UnityEngine.GUIContent content, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.Rect Window( System.Int32 id, UnityEngine.Rect screenRect, UnityEngine.GUI.WindowFunction func, System.String text, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.Rect Window( System.Int32 id, UnityEngine.Rect screenRect, UnityEngine.GUI.WindowFunction func, UnityEngine.Texture image, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.Rect Window( System.Int32 id, UnityEngine.Rect screenRect, UnityEngine.GUI.WindowFunction func, UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.GUILayoutOption Width( System.Single width ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.GUILayoutOption MinWidth( System.Single minWidth ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.GUILayoutOption MaxWidth( System.Single maxWidth ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.GUILayoutOption Height( System.Single height ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.GUILayoutOption MinHeight( System.Single minHeight ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.GUILayoutOption MaxHeight( System.Single maxHeight ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.GUILayoutOption ExpandWidth( System.Boolean expand ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.GUILayoutOption ExpandHeight( System.Boolean expand ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public GUILayout( ){
		//Mock Data:
			m_functionCallCounts = new Dictionary<string, int>();
		if(!m_functionCallCounts.ContainsKey( "Void .ctor()" )){
			m_functionCallCounts.Add( "Void .ctor()", 0 );
		}
		m_functionCallCounts["Void .ctor()"]++;
			
	}
}
}
