using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace UnityEngine {
public class GUIUtility {
	// Mock data:
	private Dictionary<string, int> m_functionCallCounts;
	public Dictionary<string, int> FunctionCallCounts {
		get { 
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			return m_functionCallCounts;
		}
	}

	public static System.Int32 GetControlID( UnityEngine.FocusType focus ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 GetControlID( System.Int32 hint, UnityEngine.FocusType focus ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 GetControlID( UnityEngine.GUIContent contents, UnityEngine.FocusType focus ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 GetControlID( UnityEngine.FocusType focus, UnityEngine.Rect position ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 GetControlID( System.Int32 hint, UnityEngine.FocusType focus, UnityEngine.Rect position ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 GetControlID( UnityEngine.GUIContent contents, UnityEngine.FocusType focus, UnityEngine.Rect position ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Object GetStateObject( System.Type t, System.Int32 controlID ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Object QueryStateObject( System.Type t, System.Int32 controlID ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static void ExitGUI( ){
	}

	public static UnityEngine.GUISkin GetBuiltinSkin( System.Int32 skin ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.Vector2 GUIToScreenPoint( UnityEngine.Vector2 guiPoint ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.Vector2 ScreenToGUIPoint( UnityEngine.Vector2 screenPoint ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static void RotateAroundPivot( System.Single angle, UnityEngine.Vector2 pivotPoint ){
	}

	public static void ScaleAroundPivot( UnityEngine.Vector2 scale, UnityEngine.Vector2 pivotPoint ){
	}

	public GUIUtility( ){
		//Mock Data:
			m_functionCallCounts = new Dictionary<string, int>();
		if(!m_functionCallCounts.ContainsKey( "Void .ctor()" )){
			m_functionCallCounts.Add( "Void .ctor()", 0 );
		}
		m_functionCallCounts["Void .ctor()"]++;
			
	}

	public static System.Int32 hotControl {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
		}
	}

	public static System.Int32 keyboardControl {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
		}
	}
}
}
