using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace UnityEngine {
public class Joint : UnityEngine.Component {
	// Mock data:
	private Dictionary<string, int> m_functionCallCounts;
	public Dictionary<string, int> FunctionCallCounts {
		get { 
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			return m_functionCallCounts;
		}
	}

	public Joint( ){
		//Mock Data:
			m_functionCallCounts = new Dictionary<string, int>();
		if(!m_functionCallCounts.ContainsKey( "Void .ctor()" )){
			m_functionCallCounts.Add( "Void .ctor()", 0 );
		}
		m_functionCallCounts["Void .ctor()"]++;
			
	}

	public System.Single breakForce {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_breakForce" )){
				m_functionCallCounts.Add( "get_breakForce", 0 );
			}
			m_functionCallCounts["get_breakForce"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "set_breakForce" )){
				m_functionCallCounts.Add( "set_breakForce", 0 );
			}
			m_functionCallCounts["set_breakForce"]++;
			
		}
	}

	public System.Single breakTorque {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_breakTorque" )){
				m_functionCallCounts.Add( "get_breakTorque", 0 );
			}
			m_functionCallCounts["get_breakTorque"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "set_breakTorque" )){
				m_functionCallCounts.Add( "set_breakTorque", 0 );
			}
			m_functionCallCounts["set_breakTorque"]++;
			
		}
	}

	public UnityEngine.Vector3 axis {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_axis" )){
				m_functionCallCounts.Add( "get_axis", 0 );
			}
			m_functionCallCounts["get_axis"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "set_axis" )){
				m_functionCallCounts.Add( "set_axis", 0 );
			}
			m_functionCallCounts["set_axis"]++;
			
		}
	}

	public UnityEngine.Vector3 anchor {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_anchor" )){
				m_functionCallCounts.Add( "get_anchor", 0 );
			}
			m_functionCallCounts["get_anchor"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "set_anchor" )){
				m_functionCallCounts.Add( "set_anchor", 0 );
			}
			m_functionCallCounts["set_anchor"]++;
			
		}
	}

	public UnityEngine.Rigidbody connectedBody {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_connectedBody" )){
				m_functionCallCounts.Add( "get_connectedBody", 0 );
			}
			m_functionCallCounts["get_connectedBody"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "set_connectedBody" )){
				m_functionCallCounts.Add( "set_connectedBody", 0 );
			}
			m_functionCallCounts["set_connectedBody"]++;
			
		}
	}
}
}
