using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace UnityEngine {
public class MeshCollider : UnityEngine.Collider {
	// Mock data:
	private Dictionary<string, int> m_functionCallCounts;
	public Dictionary<string, int> FunctionCallCounts {
		get { 
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			return m_functionCallCounts;
		}
	}

	public MeshCollider( ){
		//Mock Data:
			m_functionCallCounts = new Dictionary<string, int>();
		if(!m_functionCallCounts.ContainsKey( "Void .ctor()" )){
			m_functionCallCounts.Add( "Void .ctor()", 0 );
		}
		m_functionCallCounts["Void .ctor()"]++;
			
	}

	public System.Boolean smoothSphereCollisions {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_smoothSphereCollisions" )){
				m_functionCallCounts.Add( "get_smoothSphereCollisions", 0 );
			}
			m_functionCallCounts["get_smoothSphereCollisions"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "set_smoothSphereCollisions" )){
				m_functionCallCounts.Add( "set_smoothSphereCollisions", 0 );
			}
			m_functionCallCounts["set_smoothSphereCollisions"]++;
			
		}
	}

	public UnityEngine.Mesh sharedMesh {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_sharedMesh" )){
				m_functionCallCounts.Add( "get_sharedMesh", 0 );
			}
			m_functionCallCounts["get_sharedMesh"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "set_sharedMesh" )){
				m_functionCallCounts.Add( "set_sharedMesh", 0 );
			}
			m_functionCallCounts["set_sharedMesh"]++;
			
		}
	}

	public System.Boolean convex {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_convex" )){
				m_functionCallCounts.Add( "get_convex", 0 );
			}
			m_functionCallCounts["get_convex"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "set_convex" )){
				m_functionCallCounts.Add( "set_convex", 0 );
			}
			m_functionCallCounts["set_convex"]++;
			
		}
	}

	public UnityEngine.Mesh mesh {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_mesh" )){
				m_functionCallCounts.Add( "get_mesh", 0 );
			}
			m_functionCallCounts["get_mesh"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "set_mesh" )){
				m_functionCallCounts.Add( "set_mesh", 0 );
			}
			m_functionCallCounts["set_mesh"]++;
			
		}
	}
}
}
