using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace UnityEngine {
public class Network {
	// Mock data:
	private Dictionary<string, int> m_functionCallCounts;
	public Dictionary<string, int> FunctionCallCounts {
		get { 
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			return m_functionCallCounts;
		}
	}

	public static UnityEngine.NetworkConnectionError InitializeServer( System.Int32 connections, System.Int32 listenPort ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static void InitializeSecurity( ){
	}

	public static UnityEngine.NetworkConnectionError Connect( System.String IP, System.Int32 remotePort ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.NetworkConnectionError Connect( System.String IP, System.Int32 remotePort, System.String password ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.NetworkConnectionError Connect( System.String[] IPs, System.Int32 remotePort ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.NetworkConnectionError Connect( System.String[] IPs, System.Int32 remotePort, System.String password ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static void Disconnect( System.Int32 timeout ){
	}

	public static void Disconnect( ){
	}

	public static void CloseConnection( UnityEngine.NetworkPlayer target, System.Boolean sendDisconnectionNotification ){
	}

	public static UnityEngine.NetworkViewID AllocateViewID( ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.Object Instantiate( UnityEngine.Object prefab, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, System.Int32 group ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static void Destroy( UnityEngine.NetworkViewID viewID ){
	}

	public static void Destroy( UnityEngine.GameObject gameObject ){
	}

	public static void DestroyPlayerObjects( UnityEngine.NetworkPlayer playerID ){
	}

	public static void RemoveRPCs( UnityEngine.NetworkPlayer playerID ){
	}

	public static void RemoveRPCs( UnityEngine.NetworkPlayer playerID, System.Int32 group ){
	}

	public static void RemoveRPCsInGroup( System.Int32 group ){
	}

	public static void RemoveRPCs( UnityEngine.NetworkViewID viewID ){
	}

	public static void SetLevelPrefix( System.Int32 prefix ){
	}

	public static System.Int32 GetLastPing( UnityEngine.NetworkPlayer player ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Int32 GetAveragePing( UnityEngine.NetworkPlayer player ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static void SetReceivingEnabled( UnityEngine.NetworkPlayer player, System.Int32 group, System.Boolean enabled ){
	}

	public static void SetSendingEnabled( System.Int32 group, System.Boolean enabled ){
	}

	public static void SetSendingEnabled( UnityEngine.NetworkPlayer player, System.Int32 group, System.Boolean enabled ){
	}

	public static UnityEngine.ConnectionTesterStatus TestConnection( System.Boolean forceTest ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.ConnectionTesterStatus TestConnection( ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.ConnectionTesterStatus TestConnectionNAT( ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Boolean HavePublicAddress( ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public Network( ){
		//Mock Data:
			m_functionCallCounts = new Dictionary<string, int>();
		if(!m_functionCallCounts.ContainsKey( "Void .ctor()" )){
			m_functionCallCounts.Add( "Void .ctor()", 0 );
		}
		m_functionCallCounts["Void .ctor()"]++;
			
	}

	public static System.Int32 natFacilitatorPort {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
		}
	}

	public static System.Double time {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public static System.String proxyIP {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
		}
	}

	public static System.Boolean useProxy {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
		}
	}

	public static System.Int32 proxyPort {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
		}
	}

	public static System.String incomingPassword {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
		}
	}

	public static System.String natFacilitatorIP {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
		}
	}

	public static System.Boolean useNat {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
		}
	}

	public static UnityEngine.NetworkPeerType peerType {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public static System.Boolean isClient {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public static UnityEngine.NetworkPlayer player {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public static System.String connectionTesterIP {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
		}
	}

	public static System.Int32 maxConnections {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
		}
	}

	public static System.Boolean isMessageQueueRunning {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
		}
	}

	public static System.String proxyPassword {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
		}
	}

	public static UnityEngine.NetworkPlayer[] connections {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public static System.Int32 connectionTesterPort {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
		}
	}

	public static System.Int32 minimumAllocatableViewIDs {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
		}
	}

	public static System.Boolean isServer {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public static System.Single sendRate {
		get {
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
		}
	}
}
}
