using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace UnityEngine {
public class StackTraceUtility {
	// Mock data:
	private Dictionary<string, int> m_functionCallCounts;
	public Dictionary<string, int> FunctionCallCounts {
		get { 
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			return m_functionCallCounts;
		}
	}

	public static void SetProjectFolder( System.String folder ){
	}

	public static System.String ExtractStackTrace( ){
		System.Diagnostics.StackTrace st = new System.Diagnostics.StackTrace();
		return st.ToString();
	}

	public static System.String ExtractStringFromException( System.Exception exception ){
		System.Diagnostics.StackTrace st = new System.Diagnostics.StackTrace(exception);
		return st.ToString();
	}

	public static System.Text.StringBuilder NicifyStacktrace( System.String oldString ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Text.StringBuilder ProcessSplitCleanup( System.Collections.ArrayList cleanedUpsplit ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.Text.StringBuilder ExtractFormattedStackTrace( System.Diagnostics.StackTrace stackTrace ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public StackTraceUtility( ){
		//Mock Data:
			m_functionCallCounts = new Dictionary<string, int>();
		if(!m_functionCallCounts.ContainsKey( "Void .ctor()" )){
			m_functionCallCounts.Add( "Void .ctor()", 0 );
		}
		m_functionCallCounts["Void .ctor()"]++;
			
	}
}
}
