using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace UnityEngine {
public class WWW {
	// Mock data:
	private Dictionary<string, int> m_functionCallCounts;
	public Dictionary<string, int> FunctionCallCounts {
		get { 
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			return m_functionCallCounts;
		}
	}

	public virtual void Dispose( ){
		//Mock Data:
		if(m_functionCallCounts == null) {
			m_functionCallCounts = new Dictionary<string, int>();
		}
		if(!m_functionCallCounts.ContainsKey( "Void Dispose()" )){
			m_functionCallCounts.Add( "Void Dispose()", 0 );
		}
		m_functionCallCounts["Void Dispose()"]++;
			
	}

	public void InitWWW( System.String url, System.Byte[] postData, System.String[] iHeaders ){
		//Mock Data:
		if(m_functionCallCounts == null) {
			m_functionCallCounts = new Dictionary<string, int>();
		}
		if(!m_functionCallCounts.ContainsKey( "Void InitWWW(System.String, System.Byte[], System.String[])" )){
			m_functionCallCounts.Add( "Void InitWWW(System.String, System.Byte[], System.String[])", 0 );
		}
		m_functionCallCounts["Void InitWWW(System.String, System.Byte[], System.String[])"]++;
			
	}

	public static System.String EscapeURL( System.String s ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.String EscapeURL( System.String s, System.Text.Encoding e ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.String UnEscapeURL( System.String s ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static System.String UnEscapeURL( System.String s, System.Text.Encoding e ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public void LoadImageIntoTexture( UnityEngine.Texture2D tex ){
		//Mock Data:
		if(m_functionCallCounts == null) {
			m_functionCallCounts = new Dictionary<string, int>();
		}
		if(!m_functionCallCounts.ContainsKey( "Void LoadImageIntoTexture(UnityEngine.Texture2D)" )){
			m_functionCallCounts.Add( "Void LoadImageIntoTexture(UnityEngine.Texture2D)", 0 );
		}
		m_functionCallCounts["Void LoadImageIntoTexture(UnityEngine.Texture2D)"]++;
			
	}

	public static System.String GetURL( System.String url ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public static UnityEngine.Texture2D GetTextureFromURL( System.String url ){
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public void LoadUnityWeb( ){
		//Mock Data:
		if(m_functionCallCounts == null) {
			m_functionCallCounts = new Dictionary<string, int>();
		}
		if(!m_functionCallCounts.ContainsKey( "Void LoadUnityWeb()" )){
			m_functionCallCounts.Add( "Void LoadUnityWeb()", 0 );
		}
		m_functionCallCounts["Void LoadUnityWeb()"]++;
			
	}

	public WWW( System.String url ){
		//Mock Data:
			m_functionCallCounts = new Dictionary<string, int>();
		if(!m_functionCallCounts.ContainsKey( "Void .ctor(String)" )){
			m_functionCallCounts.Add( "Void .ctor(String)", 0 );
		}
		m_functionCallCounts["Void .ctor(String)"]++;
			
	}

	public WWW( System.String url, UnityEngine.WWWForm form ){
		//Mock Data:
			m_functionCallCounts = new Dictionary<string, int>();
		if(!m_functionCallCounts.ContainsKey( "Void .ctor(String, WWWForm)" )){
			m_functionCallCounts.Add( "Void .ctor(String, WWWForm)", 0 );
		}
		m_functionCallCounts["Void .ctor(String, WWWForm)"]++;
			
	}

	public WWW( System.String url, System.Byte[] postData ){
		//Mock Data:
			m_functionCallCounts = new Dictionary<string, int>();
		if(!m_functionCallCounts.ContainsKey( "Void .ctor(String, Byte[])" )){
			m_functionCallCounts.Add( "Void .ctor(String, Byte[])", 0 );
		}
		m_functionCallCounts["Void .ctor(String, Byte[])"]++;
			
	}

	public WWW( System.String url, System.Byte[] postData, System.Collections.Hashtable headers ){
		//Mock Data:
			m_functionCallCounts = new Dictionary<string, int>();
		if(!m_functionCallCounts.ContainsKey( "Void .ctor(String, Byte[], Hashtable)" )){
			m_functionCallCounts.Add( "Void .ctor(String, Byte[], Hashtable)", 0 );
		}
		m_functionCallCounts["Void .ctor(String, Byte[], Hashtable)"]++;
			
	}

	public System.String error {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_error" )){
				m_functionCallCounts.Add( "get_error", 0 );
			}
			m_functionCallCounts["get_error"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public System.String url {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_url" )){
				m_functionCallCounts.Add( "get_url", 0 );
			}
			m_functionCallCounts["get_url"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public System.Single progress {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_progress" )){
				m_functionCallCounts.Add( "get_progress", 0 );
			}
			m_functionCallCounts["get_progress"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public UnityEngine.AudioClip oggVorbis {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_oggVorbis" )){
				m_functionCallCounts.Add( "get_oggVorbis", 0 );
			}
			m_functionCallCounts["get_oggVorbis"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public UnityEngine.AssetBundle assetBundle {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_assetBundle" )){
				m_functionCallCounts.Add( "get_assetBundle", 0 );
			}
			m_functionCallCounts["get_assetBundle"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public System.Boolean isDone {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_isDone" )){
				m_functionCallCounts.Add( "get_isDone", 0 );
			}
			m_functionCallCounts["get_isDone"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public System.String data {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_data" )){
				m_functionCallCounts.Add( "get_data", 0 );
			}
			m_functionCallCounts["get_data"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public UnityEngine.MovieTexture movie {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_movie" )){
				m_functionCallCounts.Add( "get_movie", 0 );
			}
			m_functionCallCounts["get_movie"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public UnityEngine.Texture2D texture {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_texture" )){
				m_functionCallCounts.Add( "get_texture", 0 );
			}
			m_functionCallCounts["get_texture"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public System.Int32 size {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_size" )){
				m_functionCallCounts.Add( "get_size", 0 );
			}
			m_functionCallCounts["get_size"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public UnityEngine.AudioClip audioClip {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_audioClip" )){
				m_functionCallCounts.Add( "get_audioClip", 0 );
			}
			m_functionCallCounts["get_audioClip"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public System.Byte[] bytes {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_bytes" )){
				m_functionCallCounts.Add( "get_bytes", 0 );
			}
			m_functionCallCounts["get_bytes"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public System.Single uploadProgress {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_uploadProgress" )){
				m_functionCallCounts.Add( "get_uploadProgress", 0 );
			}
			m_functionCallCounts["get_uploadProgress"]++;
			
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}
}
}
