using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace UnityEditor {
[System.AttributeUsageAttribute(AttributeTargets.All)]
public class MenuItem : System.Attribute {
	// Mock data:
	private Dictionary<string, int> m_functionCallCounts;
	public Dictionary<string, int> FunctionCallCounts {
		get { 
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			return m_functionCallCounts;
		}
	}

	public MenuItem( System.String itemName, System.Boolean isValidateFunction, System.Int32 priority ){
		//Mock Data:
			m_functionCallCounts = new Dictionary<string, int>();
		if(!m_functionCallCounts.ContainsKey( "Void .ctor(String, Boolean, Int32)" )){
			m_functionCallCounts.Add( "Void .ctor(String, Boolean, Int32)", 0 );
		}
		m_functionCallCounts["Void .ctor(String, Boolean, Int32)"]++;
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public MenuItem( System.String itemName, System.Boolean isValidateFunction ){
		//Mock Data:
			m_functionCallCounts = new Dictionary<string, int>();
		if(!m_functionCallCounts.ContainsKey( "Void .ctor(String, Boolean)" )){
			m_functionCallCounts.Add( "Void .ctor(String, Boolean)", 0 );
		}
		m_functionCallCounts["Void .ctor(String, Boolean)"]++;
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public MenuItem( System.String itemName ){
		//Mock Data:
			m_functionCallCounts = new Dictionary<string, int>();
		if(!m_functionCallCounts.ContainsKey( "Void .ctor(String)" )){
			m_functionCallCounts.Add( "Void .ctor(String)", 0 );
		}
		m_functionCallCounts["Void .ctor(String)"]++;
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}
}
}
