using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace UnityEditor {
public class SerializedObject {
	// Mock data:
	private Dictionary<string, int> m_functionCallCounts;
	public Dictionary<string, int> FunctionCallCounts {
		get { 
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			return m_functionCallCounts;
		}
	}

	public void Update( ){
		//Mock Data:
		if(m_functionCallCounts == null) {
			m_functionCallCounts = new Dictionary<string, int>();
		}
		if(!m_functionCallCounts.ContainsKey( "Void Update()" )){
			m_functionCallCounts.Add( "Void Update()", 0 );
		}
		m_functionCallCounts["Void Update()"]++;
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public UnityEditor.SerializedProperty GetIterator( ){
		//Mock Data:
		if(m_functionCallCounts == null) {
			m_functionCallCounts = new Dictionary<string, int>();
		}
		if(!m_functionCallCounts.ContainsKey( "UnityEditor.SerializedProperty GetIterator()" )){
			m_functionCallCounts.Add( "UnityEditor.SerializedProperty GetIterator()", 0 );
		}
		m_functionCallCounts["UnityEditor.SerializedProperty GetIterator()"]++;
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public System.Boolean ApplyModifiedProperties( ){
		//Mock Data:
		if(m_functionCallCounts == null) {
			m_functionCallCounts = new Dictionary<string, int>();
		}
		if(!m_functionCallCounts.ContainsKey( "Boolean ApplyModifiedProperties()" )){
			m_functionCallCounts.Add( "Boolean ApplyModifiedProperties()", 0 );
		}
		m_functionCallCounts["Boolean ApplyModifiedProperties()"]++;
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public SerializedObject( UnityEngine.Object obj ){
		//Mock Data:
			m_functionCallCounts = new Dictionary<string, int>();
		if(!m_functionCallCounts.ContainsKey( "Void .ctor(Object)" )){
			m_functionCallCounts.Add( "Void .ctor(Object)", 0 );
		}
		m_functionCallCounts["Void .ctor(Object)"]++;
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}

	public System.String[] isExpandedArray {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_isExpandedArray" )){
				m_functionCallCounts.Add( "get_isExpandedArray", 0 );
			}
			m_functionCallCounts["get_isExpandedArray"]++;
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "set_isExpandedArray" )){
				m_functionCallCounts.Add( "set_isExpandedArray", 0 );
			}
			m_functionCallCounts["set_isExpandedArray"]++;
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public System.Boolean debugMode {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_debugMode" )){
				m_functionCallCounts.Add( "get_debugMode", 0 );
			}
			m_functionCallCounts["get_debugMode"]++;
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "set_debugMode" )){
				m_functionCallCounts.Add( "set_debugMode", 0 );
			}
			m_functionCallCounts["set_debugMode"]++;
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public System.Boolean registerNextUndo {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_registerNextUndo" )){
				m_functionCallCounts.Add( "get_registerNextUndo", 0 );
			}
			m_functionCallCounts["get_registerNextUndo"]++;
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
		set {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "set_registerNextUndo" )){
				m_functionCallCounts.Add( "set_registerNextUndo", 0 );
			}
			m_functionCallCounts["set_registerNextUndo"]++;
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}

	public System.Boolean hasModifiedProperties {
		get {
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			if(!m_functionCallCounts.ContainsKey( "get_hasModifiedProperties" )){
				m_functionCallCounts.Add( "get_hasModifiedProperties", 0 );
			}
			m_functionCallCounts["get_hasModifiedProperties"]++;
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
		}
	}
}
}
