using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace UnityEditor {
public class Undo {
	// Mock data:
	private Dictionary<string, int> m_functionCallCounts;
	public Dictionary<string, int> FunctionCallCounts {
		get { 
			if(m_functionCallCounts == null) {
				m_functionCallCounts = new Dictionary<string, int>();
			}
			return m_functionCallCounts;
		}
	}

	public static void RegisterUndo( UnityEngine.Object o, System.String name ){
	}

	public static void RegisterUndo( UnityEngine.Object identifier, UnityEngine.Object[] o, System.String name ){
	}

	public static void RegisterSceneUndo( System.String name ){
	}

	public static void ClearUndo( UnityEngine.Object identifier ){
	}

	public static void PerformUndo( ){
	}

	public static void PerformRedo( ){
	}

	public static void SetSnapshotTarget( UnityEngine.Object[] objectsToUndo, System.String name ){
	}

	public static void SetSnapshotTarget( UnityEngine.Object undoObject, System.String name ){
	}

	public static void ClearSnapshotTarget( ){
	}

	public static void CreateSnapshot( ){
	}

	public static void RegisterSnapshot( ){
	}

	public Undo( ){
		//Mock Data:
			m_functionCallCounts = new Dictionary<string, int>();
		if(!m_functionCallCounts.ContainsKey( "Void .ctor()" )){
			m_functionCallCounts.Add( "Void .ctor()", 0 );
		}
		m_functionCallCounts["Void .ctor()"]++;
			throw new NotImplementedException("This function was automatically generated by Mockery and has no real implementation yet.");
	}
}
}
